#--------------------------------------------------------------------------------
# Constants used in AbletonOSC
#--------------------------------------------------------------------------------

OSC_LISTEN_PORT = 11000
OSC_RESPONSE_PORT = 11001
BANK_B_OFFSET = 8

BANK_A_TEMPO = "BANKaTEMPO"
LOOPTRACK_NAMES = [
    "LOOP1",
    "LOOP2",
    "LOOP3",
    "LOOP4",
    "LOOP5",
    "LOOP6",
    "LOOP7",
    "LOOP8",
    "LOOP9",
    "LOOP10",
    "LOOP11",
    "LOOP12",
    "LOOP13",
    "LOOP14",
    "LOOP15",
    "LOOP16"
]
PRESET_INCLUDE_TRACKS = [
    "bass",
    "piano",
    "SYNTH1",
    "SYNTH2",
    "SYNTH3",
    "FOOT",
    "violin",
    "violin2",
    "mic",
    "vocoder",
    "vocoderInput",
    "looper",
    "SuperVPlay",
    "Sampler",
    "BANKA",
    "BANKaTEMPO",
    "LOOP1",
    "LOOP2",
    "LOOP3",
    "LOOP4",
    "LOOP5",
    "LOOP6",
    "LOOP7",
    "LOOP8",
    "BANKB",
    "LOOP9",
    "LOOP10",
    "LOOP11",
    "LOOP12",
    "LOOP13",
    "LOOP14",
    "LOOP15",
    "LOOP16",
    "FOOTLOOPS",
    "FootTempo",
    "FootLoop1",
    "FootLoop2",
    "FootLoop3",
    "FootLoop4",
    "FootLoop5",
    "FootLoop6",
    "FootLoop7",
    "FootLoop8",
    "MAX",
    "IpadInput1",
    "IpadInput2",
    "IpadInput3",
    "IpadOutput1",
    "IpadOutput2",
    "IpadOutput3",
    "12Step",
    "H90Violin",
    "H90Vocal",
    "12StepFoot",
    "Korg",
    "AkaiBass",
    "AkaiKeys",
    "TestKeys",
    "MergedMidi",
    "OUTPUTS",
    "Bass Stereo",
    "Piano Stereo",
    "Violin Stereo",
    "Keys 1 Stereo",
    "Keys 2 Stereo",
    "Keys 3 Stereo",
    "Loops 1 Stereo",
    "Loops 2 Stereo",
    "Foot Loops Stereo",
    "Vocal Stereo",
    "Vocoder Stereo",
    "Tide/FX Stereo",
]
TRACKS_TO_OBSERVE_MUTE_VOLUME_SENDS = [
    "bass",
    "piano",
    "SYNTH1",
    "SYNTH2",
    "SYNTH3",
    "FOOT",
    "violin",
    "violin2",
    "mic",
    "vocoder",
    "looper",
    "SuperVPlay",
    "Sampler",
]