#--------------------------------------------------------------------------------
# Constants used in AbletonOSC
#--------------------------------------------------------------------------------

OSC_LISTEN_PORT = 11000
OSC_RESPONSE_PORT = 11001
BANK_B_OFFSET = 8

BANK_A_TEMPO = "BANKaTEMPO"
LOOPTRACK_NAMES = [
    "LOOP1",
    "LOOP2",
    "LOOP3",
    "LOOP4",
    "LOOP5",
    "LOOP6",
    "LOOP7",
    "LOOP8",
    "LOOP9",
    "LOOP10",
    "LOOP11",
    "LOOP12",
    "LOOP13",
    "LOOP14",
    "LOOP15",
    "LOOP16"
]
PRESET_INCLUDE_TRACKS = [
    { "name": "bass", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": True, "hasChains": False},
    {"name": "piano", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": True, "hasChains": False},
    {"name": "SYNTH1", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": True, "hasTransp": True, "hasChains": True},
    {"name": "SYNTH2", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": True, "hasTransp": True, "hasChains": True},
    {"name": "SYNTH3", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": True, "hasTransp": True, "hasChains": True},
    {"name": "FOOT", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": True, "hasTransp": True, "hasChains": False},
    {"name": "violin", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "violin2", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "mic", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "vocoder", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": True, "hasTransp": False, "hasChains": False},
    #"name":  {"vocoderInput", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "looper", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "SuperVPlay", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "Sampler", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": True, "hasTransp": False, "hasChains": False},
    {"name": "BANKA", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "BANKaTEMPO", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP1", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP2", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP3", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP4", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP5", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP6", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP7", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP8", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "BANKB", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP9", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP10", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP11", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP12", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP13", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP14", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP15", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "LOOP16", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "FOOTLOOPS", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "FootTempo", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "FootLoop1", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "FootLoop2", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "FootLoop3", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "FootLoop4", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "FootLoop5", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "FootLoop6", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "FootLoop7", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "FootLoop8", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    # {"name": "MAX", "observeVolume": False, "observeMute": False, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "IpadInput1", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "IpadInput2", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "IpadInput3", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "IpadOutput1", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "IpadOutput2", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "IpadOutput3", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "12Step", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "H90Violin", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "H90Vocal", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "12StepFoot", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "Korg", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "AkaiBass", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "AkaiKeys", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "TestKeys", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "MergedMidi", "observeVolume": True, "observeMute": True, "observeSends": False, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "OUTPUTS", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "Bass Stereo", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "Piano Stereo", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "Violin Stereo", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "Keys 1 Stereo", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "Keys 2 Stereo", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "Keys 3 Stereo", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "Loops 1 Stereo", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "Loops 2 Stereo", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "Foot Loops Stereo", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "Vocal Stereo", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "Vocoder Stereo", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
    {"name": "Tide/FX Stereo", "observeVolume": True, "observeMute": True, "observeSends": True, "hasPGM": False, "hasTransp": False, "hasChains": False},
]

CC_LISTENERS = [
    [16, 0],
    [17, 0]
]

NOTE_LISTENERS = [
    [0, 0],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
    [6, 0],
    [7, 0],
    [8, 0],
    [9, 0],
    [10, 0],
    [11, 0],
    [12, 0],
    [13, 0],
    [14, 0],
    [15, 0]
]